services:
    - name: app1
      url: http://localhost:3001/api/app1/health
      interval: 20s
    - name: app2
      url: http://localhost:3002/api/app2/health
      interval: 20s
    - name: app3
      url: http://localhost:3003/api/app3/health
      interval: 20s
    - name: app4
      url: http://localhost:3004/api/app4/health
      interval: 20s
    - name: app5
      url: http://localhost:3005/api/app5/health
      interval: 20s
    - name: app6
      url: http://localhost:3006/api/app6/health
      interval: 20s
    - name: app7
      url: http://localhost:3007/api/app7/health
      interval: 20s
    - name: app8
      url: http://localhost:3008/api/app8/health
      interval: 20s
    - name: app9
      url: http://localhost:3009/api/app9/health
      interval: 20s
    - name: app10
      url: http://localhost:3010/api/app10/health
      interval: 20s
    - name: app11
      url: http://localhost:3011/api/app11/health
      interval: 20s
    - name: app12
      url: http://localhost:3012/api/app12/health
      interval: 20s
    - name: app13
      url: http://localhost:3013/api/app13/health
      interval: 20s
    - name: app14
      url: http://localhost:3014/api/app14/health
      interval: 20s
    - name: app15
      url: http://localhost:3015/api/app15/health
      interval: 20s
SLO:
    availability: 99
    latency_p95: 8000ms
